//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaEmpeñoModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        public int TransaccionId { get; set; }
        public int TipoTransaccionId { get; set; }
        public int ProductoId { get; set; }
        public Nullable<System.DateTime> FechaHoraTransaccion { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual TipoTransaccion TipoTransaccion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
